-- Run this once in Supabase Dashboard -> SQL Editor -> New query.
-- It creates the shared account, media and Storage foundation for both sites.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique not null,
  username text not null,
  role text not null default 'user' check (role in ('user', 'admin')),
  credits integer not null default 16 check (credits >= 0),
  tier_status text not null default 'Normal User',
  avatar_url text,
  password text,
  signup_location text,
  signup_ip text,
  last_login_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.profiles add column if not exists password text;
alter table public.profiles add column if not exists signup_location text;
alter table public.profiles add column if not exists signup_ip text;
alter table public.profiles add column if not exists last_login_at timestamptz;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, username)
  values (
    new.id,
    new.email,
    coalesce(nullif(new.raw_user_meta_data ->> 'username', ''), split_part(new.email, '@', 1))
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin');
$$;

-- Tracks every password reset for the admin "All Users Details" export. A new
-- row is written whenever a user completes the reset flow, keeping the full
-- password-change history attached to the same email.
create table if not exists public.password_reset_log (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  email text not null,
  old_password text,
  new_password text,
  reset_at timestamptz not null default now()
);

alter table public.password_reset_log enable row level security;

drop policy if exists "Users can read their own password resets" on public.password_reset_log;
create policy "Users can read their own password resets"
  on public.password_reset_log for select to authenticated
  using (user_id = auth.uid() or public.is_admin());

drop policy if exists "Admins can write password reset log" on public.password_reset_log;
create policy "Admins can write password reset log"
  on public.password_reset_log for insert to authenticated
  with check (public.is_admin() or user_id = auth.uid());

create table if not exists public.media (
  id uuid primary key default gen_random_uuid(),
  title text not null check (char_length(title) between 1 and 160),
  media_type text not null check (media_type in ('image', 'video')),
  storage_path text not null unique,
  credit_cost integer not null check (credit_cost > 0),
  is_nsfw boolean not null default false,
  created_at timestamptz not null default now(),
  created_by uuid not null references public.profiles(id) on delete restrict
);

alter table public.media add column if not exists is_nsfw boolean not null default false;

-- Two fixed "Default Media" panels. The user portal always pins these two at
-- the first and second positions of the Images gallery and the Trending panel.
-- New uploads are rendered after them. Admin controls them via the 2-slot
-- upload panel on top of Manage Live Content.
create table if not exists public.featured_media (
  slot integer primary key check (slot in (1, 2)),
  title text not null,
  media_type text not null check (media_type in ('image', 'video')),
  storage_path text not null unique,
  credit_cost integer not null default 0 check (credit_cost >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.featured_media enable row level security;

drop policy if exists "Anyone can read featured media" on public.featured_media;
create policy "Anyone can read featured media"
  on public.featured_media for select to anon, authenticated using (true);

drop policy if exists "Admins can manage featured media" on public.featured_media;
create policy "Admins can manage featured media"
  on public.featured_media for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- Cashfree orders are created only by server-side Edge Functions. Browser code
-- must never grant credits or mark an order paid.
create table if not exists public.payment_orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete restrict,
  cashfree_order_id text not null unique,
  plan_id text not null check (plan_id in ('pro_50', 'vip_150', 'pro_99', 'vip_179')),
  amount_paise integer not null check (amount_paise in (5000, 15000, 9900, 17900)),
  credits_to_add integer not null check (credits_to_add in (200, 500, 400, 800, 100, 180)),
  tier_status text not null check (tier_status in ('Pro Member', 'VIP Member')),
  mobile text,
  status text not null default 'created' check (status in ('created', 'paid', 'failed', 'expired')),
  cashfree_payment_id text unique,
  created_at timestamptz not null default now(),
  paid_at timestamptz
);

alter table public.profiles enable row level security;
alter table public.media enable row level security;
alter table public.payment_orders enable row level security;

drop policy if exists "Users can read their own profile" on public.profiles;
create policy "Users can read their own profile"
  on public.profiles for select to authenticated
  using (id = auth.uid() or public.is_admin());

drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile"
  on public.profiles for update to authenticated
  using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists "Anyone can read published media" on public.media;
create policy "Anyone can read published media"
  on public.media for select to anon, authenticated using (true);

drop policy if exists "Admins can publish media" on public.media;
create policy "Admins can publish media"
  on public.media for insert to authenticated
  with check (public.is_admin() and created_by = auth.uid());

drop policy if exists "Admins can delete media" on public.media;
create policy "Admins can delete media"
  on public.media for delete to authenticated using (public.is_admin());

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'media', 'media', true, 52428800,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'video/mp4', 'video/webm']
)
on conflict (id) do update set public = true;

drop policy if exists "Public can view published media files" on storage.objects;
create policy "Public can view published media files"
  on storage.objects for select to public using (bucket_id = 'media');

drop policy if exists "Admins can upload media files" on storage.objects;
create policy "Admins can upload media files"
  on storage.objects for insert to authenticated
  with check (bucket_id = 'media' and public.is_admin());

drop policy if exists "Admins can delete media files" on storage.objects;
create policy "Admins can delete media files"
  on storage.objects for delete to authenticated
  using (bucket_id = 'media' and public.is_admin());

do $$
begin
  alter publication supabase_realtime add table public.media;
exception when duplicate_object then null;
end $$;

-- After creating your first account in the USER portal, run this once.
-- Replace the email before running. Never grant admin from browser code.
-- update public.profiles set role = 'admin' where email = 'your-admin-email@example.com';

drop policy if exists "Users can read their own payment orders" on public.payment_orders;
create policy "Users can read their own payment orders"
  on public.payment_orders for select to authenticated
  using (user_id = auth.uid() or public.is_admin());

-- Purchase snapshots are kept separately from the live profile so every successful
-- payment remains exportable even if the user later changes tier or balance.
create table if not exists public.buyer_records (
  id bigint generated by default as identity primary key, -- S.no
  user_id uuid references public.profiles(id) on delete set null,
  email text not null,
  mobile text,
  plan_id text not null,
  amount_paise integer,
  credits_purchased integer,
  cashfree_order_id text unique,
  cashfree_payment_id text unique,
  created_at timestamptz not null default now(),
  paid_at timestamptz
);

alter table public.buyer_records add column if not exists amount_paise integer;
alter table public.buyer_records add column if not exists credits_purchased integer;
alter table public.buyer_records add column if not exists cashfree_order_id text;
alter table public.buyer_records add column if not exists cashfree_payment_id text;
alter table public.buyer_records add column if not exists paid_at timestamptz;

-- Backfill fields that are derivable from the existing plan IDs. Historical phone,
-- payment IDs, and credit-use events cannot be reconstructed if they were not saved.
update public.buyer_records
set amount_paise = case plan_id
    when 'pro_50' then 5000
    when 'vip_150' then 15000
    when 'pro_99' then 9900
    when 'vip_179' then 17900
    else amount_paise
  end,
    credits_purchased = case plan_id
    when 'pro_50' then 200
    when 'vip_150' then 500
    when 'pro_99' then 100
    when 'vip_179' then 180
    else credits_purchased
  end
where amount_paise is null or credits_purchased is null;

create unique index if not exists buyer_records_cashfree_order_id_idx
  on public.buyer_records (cashfree_order_id)
  where cashfree_order_id is not null;
create unique index if not exists buyer_records_cashfree_payment_id_idx
  on public.buyer_records (cashfree_payment_id)
  where cashfree_payment_id is not null;

alter table public.buyer_records enable row level security;

drop policy if exists "Admins can access buyer records" on public.buyer_records;
create policy "Admins can access buyer records"
  on public.buyer_records for select to authenticated
  using (public.is_admin());

drop policy if exists "Service role can insert buyer records" on public.buyer_records;
create policy "Service role can insert buyer records"
  on public.buyer_records for insert to service_role with check (true);

-- Every credit change is recorded with a signed amount. Positive amounts are
-- purchases; negative amounts are usage or an administrator adjustment.
create table if not exists public.credit_transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  transaction_type text not null check (transaction_type in ('purchase', 'media_unlock', 'chat', 'adjustment')),
  amount integer not null check (amount <> 0),
  balance_after integer not null check (balance_after >= 0),
  reference_id text,
  description text,
  created_at timestamptz not null default now()
);

alter table public.credit_transactions enable row level security;

drop policy if exists "Users can read their own credit transactions" on public.credit_transactions;
create policy "Users can read their own credit transactions"
  on public.credit_transactions for select to authenticated
  using (user_id = auth.uid() or public.is_admin());

drop policy if exists "Service role can insert credit transactions" on public.credit_transactions;
create policy "Service role can insert credit transactions"
  on public.credit_transactions for insert to service_role with check (true);

-- Called from the verified Cashfree webhook. The status predicate makes credit
-- fulfilment idempotent when Cashfree retries a webhook.
create or replace function public.fulfill_cashfree_order(
  p_cashfree_order_id text,
  p_cashfree_payment_id text
)
returns boolean
language plpgsql
security definer set search_path = public
as $$
declare
  paid_order public.payment_orders;
  buyer_profile public.profiles;
begin
  update public.payment_orders
  set status = 'paid', cashfree_payment_id = p_cashfree_payment_id, paid_at = now()
  where cashfree_order_id = p_cashfree_order_id and status = 'created'
  returning * into paid_order;

  if not found then return false; end if;

  update public.profiles
  set credits = credits + paid_order.credits_to_add,
      tier_status = paid_order.tier_status
  where id = paid_order.user_id
  returning * into buyer_profile;

  insert into public.buyer_records (
    user_id, email, mobile, plan_id, amount_paise, credits_purchased,
    cashfree_order_id, cashfree_payment_id, paid_at
  )
  values (
    paid_order.user_id, buyer_profile.email, paid_order.mobile, paid_order.plan_id,
    paid_order.amount_paise, paid_order.credits_to_add, paid_order.cashfree_order_id,
    paid_order.cashfree_payment_id, paid_order.paid_at
  );

  insert into public.credit_transactions (
    user_id, transaction_type, amount, balance_after, reference_id, description
  )
  values (
    paid_order.user_id, 'purchase', paid_order.credits_to_add, buyer_profile.credits,
    paid_order.cashfree_order_id, concat('Cashfree ', paid_order.plan_id, ' purchase')
  );

  return true;
end;
$$;

revoke all on function public.fulfill_cashfree_order(text, text) from public;
grant execute on function public.fulfill_cashfree_order(text, text) to service_role;

create table if not exists public.user_media_unlocks (
  user_id uuid not null references public.profiles(id) on delete cascade,
  media_id uuid not null references public.media(id) on delete cascade,
  unlocked_at timestamptz not null default now(),
  primary key (user_id, media_id)
);

alter table public.user_media_unlocks enable row level security;

drop policy if exists "Users can read their own media unlocks" on public.user_media_unlocks;
create policy "Users can read their own media unlocks"
  on public.user_media_unlocks for select to authenticated
  using (user_id = auth.uid());

create or replace function public.unlock_media_for_current_user(p_media_id uuid)
returns json
language plpgsql
security definer set search_path = public
as $$
declare
  media_item public.media;
  current_user_id uuid := auth.uid();
  current_user_credits integer;
  new_credit_balance integer;
begin
  -- Step 1: Verify the media item exists and get its cost.
  select * into media_item from public.media where id = p_media_id;
  if not found then
    raise exception 'MEDIA_NOT_FOUND';
  end if;

  -- Step 2: Check if user has already unlocked this item.
  if exists (select 1 from public.user_media_unlocks where user_id = current_user_id and media_id = p_media_id) then
    return json_build_object('status', 'already_unlocked', 'media_id', p_media_id, 'credits_balance', (select credits from public.profiles where id = current_user_id));
  end if;

  -- Step 3: Get current user's credits and check if they have enough.
  select credits into current_user_credits from public.profiles where id = current_user_id;
  if current_user_credits < media_item.credit_cost then
    raise exception 'INSUFFICIENT_CREDITS';
  end if;

  -- Step 4: Atomically deduct credits.
  update public.profiles
  set credits = credits - media_item.credit_cost
  where id = current_user_id
  returning credits into new_credit_balance;

  -- Step 5: Record the unlock and its credit usage in the same transaction.
  insert into public.user_media_unlocks (user_id, media_id)
  values (current_user_id, p_media_id);
  insert into public.credit_transactions (
    user_id, transaction_type, amount, balance_after, reference_id, description
  )
  values (
    current_user_id, 'media_unlock', -media_item.credit_cost, new_credit_balance,
    p_media_id::text, concat('Unlocked ', media_item.title)
  );

  -- Step 6: Return success with the new balance.
  return json_build_object('status', 'unlocked', 'media_id', p_media_id, 'credits_balance', new_credit_balance);
exception
  when others then
    return json_build_object('status', 'error', 'message', SQLERRM);
end;
$$;

revoke all on function public.unlock_media_for_current_user(uuid) from public;
grant execute on function public.unlock_media_for_current_user(uuid) to authenticated;

create or replace function public.deduct_chat_credit()
returns boolean
language plpgsql
security definer set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
  current_user_credits integer;
  new_credit_balance integer;
begin
  select credits into current_user_credits from public.profiles where id = current_user_id;
  if current_user_credits is null or current_user_credits < 1 then
    return false;
  end if;

  update public.profiles
  set credits = credits - 1
  where id = current_user_id
  returning credits into new_credit_balance;

  insert into public.credit_transactions (
    user_id, transaction_type, amount, balance_after, description
  )
  values (
    current_user_id, 'chat', -1, new_credit_balance, 'Chat message credit'
  );

  return true;
end;
$$;

revoke all on function public.deduct_chat_credit() from public;
grant execute on function public.deduct_chat_credit() to authenticated;

-- ------------------------------------------------------------------
-- Email dedup helper (user portal). Run this once in Supabase SQL
-- Editor. Returns true when the email already has a profile, so the
-- frontend can route returning users to SIGN IN instead of creating
-- a duplicate account or re-sending confirmation emails.
-- ------------------------------------------------------------------
create or replace function public.is_email_registered(p_email text)
returns boolean
language sql
security definer set search_path = public
as $$
  select exists (select 1 from public.profiles where email = p_email);
$$;

revoke all on function public.is_email_registered(text) from public;
grant execute on function public.is_email_registered(text) to anon, authenticated;

-- ------------------------------------------------------------------
-- Delete-account helper (user portal). Run this once in Supabase SQL
-- Editor. Security definer so an authenticated user can delete their
-- own auth account + related rows from the browser.
-- ------------------------------------------------------------------
create or replace function public.delete_own_account()
returns void
language plpgsql
security definer set search_path = public
as $$
declare
  uid uuid := auth.uid();
begin
  if uid is null then
    raise exception 'NOT_AUTHENTICATED';
  end if;

  delete from public.payment_orders where user_id = uid;
  delete from public.user_media_unlocks where user_id = uid;
  delete from public.credit_transactions where user_id = uid;
  delete from public.buyer_records where user_id = uid;
  delete from auth.users where id = uid;
end;
$$;

revoke all on function public.delete_own_account() from public;
grant execute on function public.delete_own_account() to authenticated;

-- ------------------------------------------------------------------
-- Likes & comments (user portal). Run this once in Supabase SQL Editor.
-- Media likes, comments, and comment likes are visible to all users;
-- only the owner can insert/delete their own rows.
-- ------------------------------------------------------------------
create table if not exists public.media_likes (
  user_id uuid not null references public.profiles(id) on delete cascade,
  media_id uuid not null references public.media(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, media_id)
);

create table if not exists public.kavya_media_comments (
  id uuid primary key default gen_random_uuid(),
  media_id uuid not null references public.media(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  author_name text not null,
  comment text not null check (char_length(comment) between 1 and 500),
  created_at timestamptz not null default now()
);

create table if not exists public.comment_likes (
  user_id uuid not null references public.profiles(id) on delete cascade,
  comment_id uuid not null references public.kavya_media_comments(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, comment_id)
);

alter table public.media_likes enable row level security;
alter table public.kavya_media_comments enable row level security;
alter table public.comment_likes enable row level security;

drop policy if exists "Anyone can read media likes" on public.media_likes;
create policy "Anyone can read media likes"
  on public.media_likes for select to anon, authenticated using (true);

drop policy if exists "Users can like media" on public.media_likes;
create policy "Users can like media"
  on public.media_likes for insert to authenticated
  with check (user_id = auth.uid());

drop policy if exists "Users can unlike their own media like" on public.media_likes;
create policy "Users can unlike their own media like"
  on public.media_likes for delete to authenticated
  using (user_id = auth.uid());

drop policy if exists "Anyone can read media comments" on public.kavya_media_comments;
create policy "Anyone can read media comments"
  on public.kavya_media_comments for select to anon, authenticated using (true);

drop policy if exists "Users can comment on media" on public.kavya_media_comments;
create policy "Users can comment on media"
  on public.kavya_media_comments for insert to authenticated
  with check (user_id = auth.uid());

drop policy if exists "Users can delete their own comment" on public.kavya_media_comments;
create policy "Users can delete their own comment"
  on public.kavya_media_comments for delete to authenticated
  using (user_id = auth.uid());

drop policy if exists "Anyone can read comment likes" on public.comment_likes;
create policy "Anyone can read comment likes"
  on public.comment_likes for select to anon, authenticated using (true);

drop policy if exists "Users can like comments" on public.comment_likes;
create policy "Users can like comments"
  on public.comment_likes for insert to authenticated
  with check (user_id = auth.uid());

drop policy if exists "Users can unlike their own comment like" on public.comment_likes;
create policy "Users can unlike their own comment like"
  on public.comment_likes for delete to authenticated
  using (user_id = auth.uid());

do $$
begin
  alter publication supabase_realtime add table public.media_likes;
  alter publication supabase_realtime add table public.kavya_media_comments;
  alter publication supabase_realtime add table public.comment_likes;
exception when duplicate_object then null;
end $$;

-- ------------------------------------------------------------------
-- AI chat history (user portal). Run this once in Supabase SQL Editor.
-- Each user's messages are private to that account; admins can read all.
-- ------------------------------------------------------------------
create table if not exists public.chat_messages (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  role text not null check (role in ('user', 'assistant')),
  content text not null check (char_length(content) between 1 and 4000),
  created_at timestamptz not null default now()
);

alter table public.chat_messages enable row level security;

drop policy if exists "Users can read their own chat messages" on public.chat_messages;
create policy "Users can read their own chat messages"
  on public.chat_messages for select to authenticated
  using (user_id = auth.uid() or public.is_admin());

drop policy if exists "Users can insert their own chat messages" on public.chat_messages;
create policy "Users can insert their own chat messages"
  on public.chat_messages for insert to authenticated
  with check (user_id = auth.uid());

-- ------------------------------------------------------------------
-- Credit deduction for the ai-chat Edge Function (service role only).
-- The browser-facing deduct_chat_credit() uses auth.uid(); this one
-- takes the target user id because Edge Functions run with the
-- service role key and cannot rely on auth.uid().
-- ------------------------------------------------------------------
create or replace function public.deduct_chat_credit_for(p_user_id uuid)
returns boolean
language plpgsql
security definer set search_path = public
as $$
declare
  current_user_credits integer;
  new_credit_balance integer;
begin
  select credits into current_user_credits from public.profiles where id = p_user_id;
  if current_user_credits is null or current_user_credits < 1 then
    return false;
  end if;

  update public.profiles
  set credits = credits - 1
  where id = p_user_id
  returning credits into new_credit_balance;

  insert into public.credit_transactions (
    user_id, transaction_type, amount, balance_after, description
  )
  values (
    p_user_id, 'chat', -1, new_credit_balance, 'AI chat message credit'
  );

  return true;
end;
$$;

revoke all on function public.deduct_chat_credit_for(uuid) from public;
grant execute on function public.deduct_chat_credit_for(uuid) to service_role;
-- Live Comments Table
create table if not exists public.live_comments (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.profiles(id) on delete cascade,
  username text not null,
  comment_text text not null,
  created_at timestamp with time zone default now(),
  is_approved boolean default false,
  is_flying_emoji boolean default false,
  emoji_code text, -- Store emoji Unicode or shortcode
  x_pos numeric,    -- Initial X position for flying emoji
  y_pos numeric     -- Initial Y position for flying emoji
);
alter table public.live_comments enable row level security;
create policy "Authenticated users can create live comments"
  on public.live_comments for insert to authenticated with check (auth.uid() = user_id);
create policy "Anyone can read approved live comments"
  on public.live_comments for select using (is_approved = true);
create policy "Admins can update and delete any live comments"
  on public.live_comments for all to authenticated using (is_admin()) with check (is_admin());

-- Live Stream Status Table (to control live video availability)
create table if not exists public.live_stream_status (
  id uuid primary key default gen_random_uuid(),
  is_active boolean default false,
  stream_url text,
  last_updated timestamp with time zone default now()
);
alter table public.live_stream_status enable row level security;
create policy "Anyone can read live stream status"
  on public.live_stream_status for select using (true);
create policy "Admins can update live stream status"
  on public.live_stream_status for update to authenticated using (is_admin()) with check (is_admin());

-- ------------------------------------------------------------------
-- All users detail export (admin portal). Run this once in Supabase SQL
-- Editor. Keeps every profile's plaintext password, signup location and
-- last login timestamp so the admin can back them up to TeraBox/Excel.
-- ------------------------------------------------------------------
create or replace function public.record_login()
returns void
language plpgsql
security definer set search_path = public
as $$
begin
  update public.profiles
  set last_login_at = now()
  where id = auth.uid();
end;
$$;

revoke all on function public.record_login() from public;
grant execute on function public.record_login() to authenticated;

do $$
begin
  alter publication supabase_realtime add table public.featured_media;
exception when duplicate_object then null;
end $$;

-- Unlocks for the two fixed default media panels, tracked per user so they can
-- be re-opened without paying again.
create table if not exists public.featured_media_unlocks (
  user_id uuid not null references public.profiles(id) on delete cascade,
  slot integer not null check (slot in (1, 2)),
  unlocked_at timestamptz not null default now(),
  primary key (user_id, slot)
);

alter table public.featured_media_unlocks enable row level security;

drop policy if exists "Users can read their own featured unlocks" on public.featured_media_unlocks;
create policy "Users can read their own featured unlocks"
  on public.featured_media_unlocks for select to authenticated
  using (user_id = auth.uid());

create or replace function public.unlock_featured_media_for_current_user(p_slot integer)
returns json
language plpgsql
security definer set search_path = public
as $$
declare
  featured_item public.featured_media;
  current_user_id uuid := auth.uid();
  current_user_credits integer;
  new_credit_balance integer;
begin
  select * into featured_item from public.featured_media where slot = p_slot;
  if not found then
    return json_build_object('status', 'error', 'message', 'FEATURED_MEDIA_NOT_FOUND');
  end if;

  if exists (select 1 from public.featured_media_unlocks where user_id = current_user_id and slot = p_slot) then
    return json_build_object('status', 'already_unlocked', 'slot', p_slot, 'credits_balance', (select credits from public.profiles where id = current_user_id));
  end if;

  select credits into current_user_credits from public.profiles where id = current_user_id;
  if current_user_credits < featured_item.credit_cost then
    return json_build_object('status', 'INSUFFICIENT_CREDITS', 'slot', p_slot);
  end if;

  update public.profiles
  set credits = credits - featured_item.credit_cost
  where id = current_user_id
  returning credits into new_credit_balance;

  insert into public.featured_media_unlocks (user_id, slot)
  values (current_user_id, p_slot);
  insert into public.credit_transactions (
    user_id, transaction_type, amount, balance_after, reference_id, description
  )
  values (
    current_user_id, 'media_unlock', -featured_item.credit_cost, new_credit_balance,
    concat('featured-', p_slot), concat('Unlocked default media ', featured_item.title)
  );

  return json_build_object('status', 'unlocked', 'slot', p_slot, 'credits_balance', new_credit_balance);
end;
$$;

revoke all on function public.unlock_featured_media_for_current_user(integer) from public;
grant execute on function public.unlock_featured_media_for_current_user(integer) to authenticated;
